#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:

!pip install numpy


In [3]:
import numpy as np
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

print(array1%array2) #modulus
print(array1**array2) #power array1 to the power of arry2
print(array1 % 2) #modulus of 2

[1 2 3 4 5]
[      1     128    6561  262144 9765625]
[1 0 1 0 1]


In [4]:
import numpy as np

## create array using numpy
##create a 1D array

list1=[10, 11, 12]
print(list1)
print(type(list1))
list1 = np.array(list1)
print(list1.shape)
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) #type of array
print(arr1.shape) #shape of array (5,) 1D array with 5 elements in it  (5,1) 2D array with 5 rows and 1 column in it    (1,5) 2D array with 1 row and 5 columns in it   (5,1,1) 3D array with 5 rows and 1 column and 1 depth in it (1,5,1) 3D array with 1 row and 5 columns and 1 depth in it  (1,1,5) 3D array with 1 row and 1 column and 5 depth in it     (5,5) 2D array with 5 rows and 5 columns in it  (5,5,5) 3D array with 5 rows and 5 columns and 5 depth in it    

[10, 11, 12]
<class 'list'>
(3,)
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns in it - reshape the array to 2D array with 1 row and 5 columns 
arr2.reshape(5,1) # reshape the array to 2D array with 5 rows and 1 column


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
ne=len(arr2)
print(arr2)
print(ne)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
2
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
#np.ones((3,4))

# Create a 3D array with 2 layers, 3 rows, and 4 columns, filled with ones
array_3d = np.ones((1, 5, 5))

print("3D array of ones:")
print(array_3d)

3D array of ones:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the element at row 1, column 2
print("Element at (1, 2):", array_2d[1, 2])

# Access the first row
print("First row:", array_2d[0])

# Access the second column
print("Second column:", array_2d[:, 1])

Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]


In [16]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [18]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [20]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [22]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [23]:
import pandas as pd

data = {'Name': ['Sat1', 'Sat2', 'Sat3'],
        'Age': [10,20 , 30]}
df = pd.DataFrame(data)

print(df)

print("iloc[2, 1]")
print(df.iloc[2, 1])

print("selecting the 'Name' column AND 1st row")
print(df.loc[1, 'Name']) #selecting the 'Name' column AND 1st row

print("Selecting the 'Name' column")

   Name  Age
0  Sat1   10
1  Sat2   20
2  Sat3   30
iloc[2, 1]
30
selecting the 'Name' column AND 1st row
Sat2
Selecting the 'Name' column


In [ ]:
import pandas as pd
import numpy as np

data = {'Name': ['Sat1', 'Sat2', 'Sat3'],
        'Age': [10, np.nan, 30],
        'Salary': [50000, 60000, np.nan]}
df = pd.DataFrame(data)

print("DataFrame with missing values:")
print(df)

print("\nChecking for missing values:")
print(df.isnull())

print("\nChecking for non-missing values:")
print(df.notnull())

import pandas as pd
import numpy as np

data = {'Name': ['Sat1', 'Sat2', 'Sat3'],
        'Age': [10, np.nan, 30],
        'Salary': [50000, 60000, np.nan]}
df = pd.DataFrame(data)

print("DataFrame with missing values:")
print(df)

print("\nChecking for missing values:")
print(df.isnull())

print("\nChecking for non-missing values:")
print(df.notnull())